'use client';

import { useState, useEffect } from 'react';
import { useTranslations } from 'next-intl';
import { useLocale } from 'next-intl';
import { ArrowRight, Store, FileText, Tag, MessageCircle, CheckCircle, AlertCircle, ChevronDown, ChevronUp, Loader2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { generateSlug } from '@/lib/slug';

interface StoreCategory {
  id: number;
  name: string;
  slug: string;
}

const TERMS_VERSION = '1.0';

export default function SellerOnboardingForm() {
  const t = useTranslations('seller.onboarding');
  const locale = useLocale();
  const router = useRouter();
  const isRTL = locale === 'ar';
  const isAr = locale === 'ar';

  const [storeName, setStoreName] = useState('');
  const [storeDescription, setStoreDescription] = useState('');
  const [storeCategoryId, setStoreCategoryId] = useState('');
  const [whatsappNumber, setWhatsappNumber] = useState('');
  const [categories, setCategories] = useState<StoreCategory[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [platformFee, setPlatformFee] = useState<string>('0');

  // Terms state
  const [agreedToTerms, setAgreedToTerms] = useState(false);
  const [termsExpanded, setTermsExpanded] = useState(false);

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const response = await fetch('/api/store-categories');
        if (!response.ok) throw new Error('Failed to fetch categories');
        const data = await response.json();
        setCategories(data);
      } catch (err) {
        console.error('Error fetching categories:', err);
        setError('Failed to load categories');
      } finally {
        setCategoriesLoading(false);
      }
    };

    // Fetch platform fee to show in terms
    const fetchFee = async () => {
      try {
        const res = await fetch('/api/public/platform-fee');
        if (res.ok) {
          const data = await res.json();
          setPlatformFee(data.platformFeePerOrder ?? '0');
        }
      } catch { /* use default */ }
    };

    fetchCategories();
    fetchFee();
  }, []);

  const validatePhone = (phone: string) => {
    const phoneRegex = /^[0-9+\-\s()]{7,}$/;
    return phoneRegex.test(phone);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    if (!storeName.trim()) {
      setError(t('storeNameRequired'));
      setLoading(false);
      return;
    }

    if (!storeDescription.trim()) {
      setError(t('storeDescriptionRequired'));
      setLoading(false);
      return;
    }

    if (!storeCategoryId) {
      setError(t('storeCategoryRequired'));
      setLoading(false);
      return;
    }

    if (!whatsappNumber.trim()) {
      setError(t('whatsappRequired'));
      setLoading(false);
      return;
    }

    if (!validatePhone(whatsappNumber)) {
      setError(t('whatsappInvalid'));
      setLoading(false);
      return;
    }

    if (!agreedToTerms) {
      setError(isAr ? 'يجب الموافقة على الشروط والأحكام للمتابعة' : 'You must agree to the terms and conditions to continue');
      setLoading(false);
      return;
    }

    try {
      const response = await fetch('/api/seller/create-store', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          storeName,
          storeDescription,
          storeCategoryId: parseInt(storeCategoryId),
          whatsappNumber,
          agreedToTerms: true,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || t('error'));
        setLoading(false);
        return;
      }

      // Use the actual unique slug generated by the backend (e.g., test-1) instead of generating the base slug locally.
      router.push(`/${locale}/${data.store.slug}/admin`);
    } catch (err) {
      console.error('Store creation error:', err);
      setError('An error occurred. Please try again.');
      setLoading(false);
    }
  };

  const feeAmount = parseFloat(platformFee || '0').toFixed(2);

  const terms = isAr ? [
    {
      title: 'رسوم المنصة',
      body: `تلتزم بدفع رسوم ثابتة قدرها ${feeAmount} ج.م على كل طلب يتم تسجيله في المنصة، بصرف النظر عن حالة الطلب (مكتمل أو ملغي أو معلق). هذه الرسوم تُخصم من إيراداتك الشهرية.`,
    },
    {
      title: 'الطلبات الملغاة',
      body: 'تُطبَّق رسوم المنصة على جميع الطلبات المسجلة بما فيها الملغاة. إلغاء الطلب لا يُعفيك من رسوم المنصة المستحقة عليه.',
    },
    {
      title: 'إدارة المتجر',
      body: 'أنت المسؤول الكامل عن محتوى متجرك، بما يشمل المنتجات والأسعار والصور والأوصاف. يجب أن تكون جميع المعلومات دقيقة وصادقة.',
    },
    {
      title: 'التوصيل والشحن',
      body: 'أنت المسؤول عن تحديد مناطق التوصيل ورسوم الشحن وتنفيذ الطلبات في الوقت المناسب. SouqFlow ليست مسؤولة عن أي تأخير أو مشكلة في التوصيل.',
    },
    {
      title: 'تعليق الحساب',
      body: 'تحتفظ SouqFlow بحق تعليق أو إيقاف أي متجر يخالف سياسات المنصة أو يتلقى شكاوى متكررة من العملاء.',
    },
    {
      title: 'التعديلات على الشروط',
      body: 'قد تُعدَّل هذه الشروط من وقت لآخر. سيتم إخطارك بأي تغييرات جوهرية عبر البريد الإلكتروني المسجل.',
    },
  ] : [
    {
      title: 'Platform Fee',
      body: `You agree to pay a fixed fee of ${feeAmount} EGP per order recorded on the platform, regardless of the order status (completed, cancelled, or pending). This fee is deducted from your monthly revenue.`,
    },
    {
      title: 'Cancelled Orders',
      body: 'Platform fees apply to all recorded orders including cancelled ones. Cancelling an order does not waive the platform fee associated with it.',
    },
    {
      title: 'Store Management',
      body: 'You are solely responsible for your store content including products, prices, images, and descriptions. All information must be accurate and truthful.',
    },
    {
      title: 'Delivery & Shipping',
      body: 'You are responsible for setting delivery areas, shipping fees, and fulfilling orders in a timely manner. SouqFlow is not liable for any delivery delays or issues.',
    },
    {
      title: 'Account Suspension',
      body: 'SouqFlow reserves the right to suspend or terminate any store that violates platform policies or receives repeated customer complaints.',
    },
    {
      title: 'Terms Modifications',
      body: 'These terms may be updated from time to time. You will be notified of any material changes via your registered email address.',
    },
  ];

  const inputClass = `w-full rounded-xl border border-neutral-200 bg-white/80 py-3.5 text-neutral-900 placeholder-neutral-400 backdrop-blur-sm transition-all focus:border-emerald-500 focus:outline-none focus:ring-4 focus:ring-emerald-500/10 ${isRTL ? 'pr-11 pl-4' : 'pl-11 pr-4'}`;

  return (
    <div className="w-full">
      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Store Name */}
        <div>
          <label className="mb-1.5 block text-sm font-bold text-neutral-700 px-1">
            {t('storeNameLabel')}
          </label>
          <div className="relative group">
            <Store className={`absolute top-1/2 -translate-y-1/2 h-5 w-5 text-neutral-400 transition-colors group-focus-within:text-emerald-500 ${isRTL ? 'right-4' : 'left-4'}`} />
            <input
              type="text"
              placeholder={t('storeNamePlaceholder')}
              value={storeName}
              onChange={(e) => setStoreName(e.target.value)}
              className={inputClass}
            />
          </div>
          <p className="mt-1.5 px-1 text-xs font-medium text-neutral-400">{t('storeNameHint')}</p>
        </div>

        {/* Store Description */}
        <div>
          <label className="mb-1.5 block text-sm font-bold text-neutral-700 px-1">
            {t('storeDescriptionLabel')}
          </label>
          <div className="relative group">
            <FileText className={`absolute top-4 h-5 w-5 text-neutral-400 transition-colors group-focus-within:text-emerald-500 ${isRTL ? 'right-4' : 'left-4'}`} />
            <textarea
              placeholder={t('storeDescriptionPlaceholder')}
              value={storeDescription}
              onChange={(e) => setStoreDescription(e.target.value)}
              rows={4}
              className={`${inputClass} resize-none`}
            />
          </div>
          <p className="mt-1.5 px-1 text-xs font-medium text-neutral-400">{t('storeDescriptionHint')}</p>
        </div>

        {/* Store Category */}
        <div>
          <label className="mb-1.5 block text-sm font-bold text-neutral-700 px-1">
            {t('storeCategoryLabel')}
          </label>
          <div className="relative group">
            <Tag className={`absolute top-1/2 -translate-y-1/2 h-5 w-5 text-neutral-400 transition-colors group-focus-within:text-emerald-500 pointer-events-none ${isRTL ? 'right-4' : 'left-4'}`} />
            <select
              value={storeCategoryId}
              onChange={(e) => setStoreCategoryId(e.target.value)}
              disabled={categoriesLoading}
              className={`${inputClass} appearance-none`}
            >
              <option value="">{categoriesLoading ? 'Loading...' : t('selectCategory')}</option>
              {categories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* WhatsApp Number */}
        <div>
          <label className="mb-1.5 block text-sm font-bold text-neutral-700 px-1">
            {t('whatsappLabel')}
          </label>
          <div className="relative group">
            <MessageCircle className={`absolute top-1/2 -translate-y-1/2 h-5 w-5 text-neutral-400 transition-colors group-focus-within:text-emerald-500 ${isRTL ? 'right-4' : 'left-4'}`} />
            <input
              type="tel"
              placeholder={t('whatsappPlaceholder')}
              value={whatsappNumber}
              onChange={(e) => setWhatsappNumber(e.target.value)}
              className={inputClass}
            />
          </div>
          <p className="mt-1.5 px-1 text-xs font-medium text-neutral-400">{t('whatsappHint')}</p>
        </div>

        {/* ── Terms & Conditions ── */}
        <div className={`rounded-2xl border-2 ${agreedToTerms ? 'border-emerald-200 bg-emerald-50/50' : 'border-neutral-100 bg-white/50'} shadow-sm transition-colors duration-300`}>
          {/* Header */}
          <div className={`flex items-center justify-between px-5 py-4`}>
            <div className={`flex items-center gap-3`}>
              {agreedToTerms
                ? <CheckCircle className="h-5 w-5 text-emerald-500 shrink-0" />
                : <AlertCircle className="h-5 w-5 text-amber-500 shrink-0" />
              }
              <div>
                <p className="text-sm font-bold text-neutral-900">
                  {isAr ? 'الشروط والأحكام' : 'Terms & Conditions'}
                </p>
                <p className="text-xs font-medium text-neutral-500 mt-0.5">
                  {isAr ? `الإصدار ${TERMS_VERSION} — يجب القراءة والموافقة` : `Version ${TERMS_VERSION} — Must read and agree`}
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={() => setTermsExpanded(!termsExpanded)}
              className="flex items-center gap-1.5 rounded-xl px-4 py-2 text-xs font-bold text-emerald-600 hover:bg-emerald-50 transition-colors"
            >
              {termsExpanded
                ? (isAr ? 'إخفاء' : 'Hide')
                : (isAr ? 'قراءة الشروط' : 'Read terms')
              }
              {termsExpanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
            </button>
          </div>

          {/* Expandable terms list */}
          {termsExpanded && (
            <div className={`border-t border-neutral-100/50 px-5 py-5 space-y-5 bg-white/30`}>
              {terms.map((term, i) => (
                <div key={i} className={`flex gap-3`}>
                  <div className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-lg bg-emerald-100 text-[10px] font-black text-emerald-700">
                    {i + 1}
                  </div>
                  <div>
                    <p className="text-sm font-bold text-neutral-900">{term.title}</p>
                    <p className="mt-1 text-xs font-medium leading-relaxed text-neutral-600">{term.body}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Checkbox */}
          <div className={`border-t border-neutral-100/50 px-5 py-4 flex items-start gap-3 bg-white/50 rounded-b-2xl`}>
            <button
              type="button"
              onClick={() => setAgreedToTerms(!agreedToTerms)}
              className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border-2 transition-all ${
                agreedToTerms
                  ? 'border-emerald-500 bg-emerald-500'
                  : 'border-neutral-300 bg-white hover:border-emerald-400'
              }`}
            >
              {agreedToTerms && (
                <svg className="h-3.5 w-3.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              )}
            </button>
            <p className={`text-xs font-medium text-neutral-600 leading-relaxed`}>
              {isAr
                ? `أوافق على الشروط والأحكام المذكورة أعلاه، وأفهم أن رسوم المنصة البالغة ${feeAmount} ج.م ستُطبَّق على كل طلب بصرف النظر عن حالته.`
                : `I agree to the terms and conditions above, and I understand that a platform fee of ${feeAmount} EGP will be applied to every order regardless of its status.`
              }
            </p>
          </div>
        </div>

        {error && (
          <div className={`flex items-center gap-3 rounded-xl bg-red-50 p-4 text-sm font-medium text-red-600 border border-red-100 animate-in fade-in`}>
            <AlertCircle className="h-5 w-5 shrink-0" />
            {error}
          </div>
        )}

        <button
          type="submit"
          disabled={loading || categoriesLoading || !agreedToTerms}
          className={`relative flex w-full items-center justify-center gap-2 overflow-hidden rounded-xl py-4 font-black text-white transition-all active:scale-[0.98] disabled:opacity-70 disabled:active:scale-100 shadow-xl shadow-neutral-200 group ${
            agreedToTerms
              ? 'bg-neutral-900 hover:bg-emerald-600'
              : 'bg-neutral-300 cursor-not-allowed shadow-none'
          }`}
        >
          {loading ? (
            <Loader2 className="h-5 w-5 animate-spin" />
          ) : (
            <>
              {t('createStore')}
              <ArrowRight className={`h-5 w-5 transition-transform ${isRTL ? 'rotate-180 group-hover:-translate-x-1' : 'group-hover:translate-x-1'}`} />
            </>
          )}
        </button>
      </form>
    </div>
  );
}
